# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_postid', models.CharField(max_length=20)),
                ('m_title', models.CharField(max_length=100)),
                ('m_image', models.CharField(max_length=100)),
                ('m_duration', models.CharField(max_length=30)),
                ('m_app_fu_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=16)),
                ('u_password', models.CharField(max_length=20)),
                ('u_email', models.CharField(max_length=30)),
                ('u_icon', models.ImageField(upload_to='', verbose_name='用户头像')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='id_user',
            field=models.ManyToManyField(to='one.User'),
        ),
    ]
